### ISSUE TITLE
Errors since Pre Patch

### ISSUE THREAD

**Issue by Niyuni** [romdeau23/wow-lfgspamfilter#10]
1.
19x Interface/AddOns/LFGSpamFilter/LFGSpamFilter.xml:75 Couldn't find inherited node: OptionsCheckButtonTemplate

2.
11x FrameXML\Bindings.xml:1 Interface/AddOns/LFGSpamFilter/LFGSpamFilter.xml:75 Couldn't find inherited node: OptionsCheckButtonTemplate

**Comment by romdeau23** [comment]
Yep, multiple things are broken. Working on a fix 👷

**Comment by romdeau23** [comment]
Should be fixed in 1.3.0
