### ISSUE TITLE
this addon won't report the bad player? just banned them in local ?

### ISSUE THREAD

**Issue by wowmacro** [romdeau23/wow-lfgspamfilter#4]
I just update this addon for 9.2.5 and click the “X” button. and my chat frame doesnt show the prompt for report

**Comment by wowmacro** [comment]
if this addon won't report the bad player, what about let addon auto select the options, then let us click the report bottom by  manual.

**Comment by romdeau23** [comment]
Addons can't send the report automatically anymore so this was removed on purpose. I'll try and see if it could at least optionally open the report window.

Meanwhile you can still report them for advertising instead of clicking the "X". The addon takes note of advertising group reports and bans the leader the same way.

**Comment by wowmacro** [comment]
thank u! I reported 300 more bad players by this addon.

now I have to right click, select, click select, click, click to report them. Blizzard new report system is too fussy.

so im hoping this addon can do the right click, select, click select, click, click things for me, and Im just click the final step “report” button

**Comment by romdeau23** [comment]
I've looked into it. Sadly, pre-filling the reason and details breaks it.

Best this addon could do is open the report window, which would save you 2 out of 6 clicks.

**Comment by wowmacro** [comment]
lol 
I think it‘s better than 6 clicks.
If I report 30 times, it would save 60 clicks.

Love to see the new patch with saving clicks option

**Comment by romdeau23** [comment]
I've added a new button in version 1.2.0 that shows up after you click the "X". Click the new button that appears 3 times to report the group for advertisement. It's still 4 clicks total but you don't have to move your mouse 😄
