### ISSUE TITLE
Still seeing WTS group

### ISSUE THREAD

**Issue by blecaplol** [romdeau23/wow-lfgspamfilter#5]
Hi as per title.

**Comment by romdeau23** [comment]
If you wanted more information about why this is - addons can't read the group name or description, so filtering is not as easy as searching for phrases like "wts" or "boost".

Blizz has really gutted the ability of addons to effectively filter or report spam groups while also doing very little to enforce their own ToS 🤷 

So block groups using the red "X" button and you'll see less of them over time (unless they get replaced faster). You could also get the "Premade Groups Filter" addon and search for more specific groups, which often excludes spam groups with 1 player in them.
