### ISSUE TITLE
previous version

### ISSUE THREAD

**Issue by blecaplol** [romdeau23/wow-lfgspamfilter#6]
hey sorry not really a problem or maybe im not aware but i prefer tjhe previous version. i just click X and its gone from my menu forever which i really like because sometimes i still see ads going through with the 1 click everything goes away but the latest version require me to do a few more clicks which i dont really like. im not a coder so i dont know whats going on. i just like the 1 click away :p

**Comment by romdeau23** [comment]
You can turn off "report helper" in the options. Then it's back to 1 click with no reporting.
