### ISSUE TITLE
Bugs & errors

### ISSUE THREAD

**Issue by giurlaninick** [romdeau23/wow-lfgspamfilter#7]
Hi mate. I've recently started getting a lua error with your addon. I love it btw and it's super helful, I just have no idea what I can do to make this error go away.

1x [ADDON_ACTION_BLOCKED] AddOn 'LFGSpamFilter' tried to call the protected function 'LFGSpamFilterReportHelperButton:Hide()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Hide'
[string "@LFGSpamFilter\modules/ui.lua"]:40: in function <LFGSpamFilter\modules/ui.lua:37>
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@FrameXML\UIParent.lua"]:3001: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:3081: in function `HideUIPanel'
[string "@FrameXML\UIParent.lua"]:2734: in function <FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3602: in function <FrameXML\UIParent.lua:3585>
[string "=[C]"]: in function `HideUIPanel'
[string "@FrameXML\PVEFrame.lua"]:79: in function <FrameXML\PVEFrame.lua:64>
[string "=[C]"]: in function `PVEFrame_ToggleFrame'
[string "TOGGLEDUNGEONSANDRAIDS"]:1: in function <[string "TOGGLEDUNGEONSANDRAIDS"]:1>

**Comment by romdeau23** [comment]
Are you in combat when this happens?

**Comment by romdeau23** [comment]
It should be fixed in 1.2.1.
