### ISSUE TITLE
Tried to call the protected function 'UNKNOWN()'

### ISSUE THREAD

**Issue by Arion-Kun** [romdeau23/wow-lfgspamfilter#9]
Trace:
```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'LFGSpamFilter' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "=[C]"]: in function `SendReport'
[string "@FrameXML\ReportFrame.lua"]:171: in function `SendReport'
[string "@FrameXML\ReportFrame.lua"]:75: in function `InitiateReportInternal'
[string "@FrameXML\ReportFrame.lua"]:427: in function <FrameXML\ReportFrame.lua:413>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\ReportFrame.lua"]:52: in function `InitiateReport'
[string "@FrameXML\LFGList.lua"]:3281: in function `LFGList_ReportAdvertisement'
[string "@FrameXML\LFGList.lua"]:3313: in function `func'
[string "@SharedXML\UIDropDownMenu.lua"]:918: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

**Comment by romdeau23** [comment]
Are you trying to report spam by using "right click - report advertisement"?

**Comment by Arion-Kun** [comment]
Yes

**Comment by romdeau23** [comment]
The results table gets tainted by being filtered, so this can't really be fixed. At least not until Blizzard adds an official API to do this.

This happens with any other addon that changes the results, e.g. 0xbs/premade-groups-filter#95

Best I can do is disable that menu option or add some message.

**Comment by Arion-Kun** [comment]
Some message might work, the error only appears every once and a while, it never repeats in succession, the action still completes successfully, the only indicator of an error is the error sound from bugsack.

**Comment by romdeau23** [comment]
Ok, I'm not gonna block this action, but I can't fix it either. We'll see what the next xpac does to the APIs.
